package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/2)
=> chore: add state management 'zustand'

Jenkinsfile, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/4)
=> ci: add Jenkins

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/5)
=> feat: add big.js

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/6)
=> fix: modify the version of husky

.gitignore, src/hooks/useTheme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/8)
=> feat: add useTheme to change the dark mode

public/index.html, src/pages/App.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/9)
=> feat: add default theme

package.json, src/constants/index.js, src/constants/web3Connectors.js, src/hooks/useAddTokenToMetamask.js, src/hooks/useWeb3Network.js, src/index.js, src/utils/getLibrary.js, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/11)
=> feat(hooks): connect web3 and hooks based on web3

src/assets/images/close.svg, src/components/Button/index.js, src/components/Tag/index.js, src/pages/App.js, tailwind.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/13)
=> feat: finish tag component

src/pages/components/TokenNameAndIcon/index.js, src/pages/shuttle/TokenType.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/18)
=> refactor: add isRequired to some props

src/components/Tag/index.js, src/constants/chainConfig.js, src/pages/App.js, src/pages/Shuttle/TokenType.js, src/pages/components/TokenNameAndIcon/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/19)
=> feat(tokennameandicon): show the Subscript of origin chain

src/constants/chainConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/23)
=> feat(chainconfig): add chainIds to config file

src/constants/chainConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/24)
=> feat(chainconfig): add Wallet config to chainConfig

craco.config.js, src/utils/request.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/29)
=> refactor(proxy): refactor the proxy config

package.json, src/components/Alert/index.js, src/hooks/useWeb3Network.js, src/pages/App.js, src/pages/Example.js, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/37)
=> fix: fix error: connect metamask when init

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/43)
=> feat: add data-format npm package

src/components/Input/index.js, src/hooks/useTokenList.js, src/pages/Shuttle/ConfirmModal/ConfirmInfo.js, src/pages/Shuttle/ConfirmModal/ConfirmTips.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js, src/pages/Shuttle/ConfirmModal/index.js, src/pages/Shuttle/ShuttleForm/TokenSelect.js, src/pages/Shuttle/ShuttleForm/index.js, src/pages/Shuttle/TokenList/index.js, src/pages/Shuttle/index.js, src/pages/components/AccountStatus/index.js, src/pages/components/ConnectWallet/index.js, src/pages/components/ConnectWalletModal/index.js, src/pages/components/TokenIcon/index.js, src/pages/components/TransactionReceiptionModal/index.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/49)
=> feat: modify shuttle page

src/pages/components/TransactionReceiptionModal/index.js
only addToken to MetaMask when the toChain is based on MetaMask
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/50)
=> fix(shuttle): addToken to MetaMask 

public/locales/en.json, public/locales/zh-CN.json, src/pages/Home/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/57)
=> feat(i18n): change i18n and import in home page

src/pages/Home/index.js, tailwind.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/59)
=> feat(button): change button in home page

src/constants/chainConfig.js, src/constants/index.js, src/hooks/useTokenList.js, src/hooks/useWeb3Network.js, src/pages/Shuttle/ShuttleForm/index.js
1. fix the error: when max is 0, should display error message
2. change the remind divide value when set max of each chain
3. use useMemo instead of 'useEffect + useState' as simple
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/60)
=> feat: some upgrade

public/locales/en.json, public/locales/zh-CN.json, src/components/WrapIcon/index.js, src/hooks/useAddTokenToMetamask.js, src/hooks/useShuttleData.js, src/hooks/useTokenList.js, src/pages/Example.js, src/pages/Shuttle/ConfirmModal/ConfirmInfo.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js, src/pages/Shuttle/ConfirmModal/index.js, src/pages/Shuttle/ShuttleForm/TokenSelect.js, src/pages/Shuttle/TokenList/CommonTokens.js, src/pages/Shuttle/TokenList/TokenItem.js, src/pages/components/TransactionReceiptionModal/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/62)
=> fix: fix map token add key

src/hooks/usePortal.js, src/hooks/useWallet.js, src/hooks/useWeb3Network.js, src/pages/components/Account/index.js, src/pages/components/AccountStatus/index.js, src/pages/components/ConnectWallet/index.js, src/pages/components/ConnectWalletModal/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/66)
=> feat: fix loop render

src/pages/Home/index.js, tailwind.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/74)
=> feat(speed): change light pulse and token flow speed

src/hooks/useWeb3Network.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/76)
=> fix: fix allowance bug

src/constants/index.js, src/pages/Shuttle/ShuttleForm/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/77)
=> fix(shuttleform): fix token decimals when it is on conflux

src/components/Modal/index.js, src/pages/Shuttle/ConfirmModal/BtcConfirmTips.js, src/pages/Shuttle/ConfirmModal/ConfirmTips.js, src/pages/Shuttle/ConfirmModal/SelectedChains.js, src/pages/Shuttle/ConfirmModal/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/78)
=> feat: add id and fix bug

src/pages/components/LanguageButton/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/79)
=> fix(i18n): en-US en

src/pages/Shuttle/ShuttleForm/ChainSelect.js, src/pages/components/RiskModal/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/81)
=> feat: add id for test

src/pages/components/WalletHub/index.js, src/pages/components/useTransactionNotification/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/84)
=> feat: add history link href

src/pages/History/HistoryItem.js, src/pages/Shuttle/TokenList/TokenItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/86)
=> fix: native token don't copy address

src/hooks/usePortal.js, src/hooks/useWallet.js, src/hooks/useWeb3Network.js, src/pages/Shuttle/ShuttleForm/index.js, src/pages/Shuttle/TokenList/TokenItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/87)
=> fix: fix bugs

src/hooks/index.js, src/hooks/usePortal.js, src/pages/components/Header/index.js, src/pages/components/MobileFooter/index.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/88)
=> fix: fix several bugs

src/hooks/index.js, src/pages/History/HistoryItem.js, src/pages/Shuttle/ShuttleForm/FromToken.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/89)
=> fix: fix walletHub

src/pages/components/HeaderAccount/index.js, src/utils/address.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/92)
=> fix: fix chain id cfx address

src/constants/chainConfig.js, src/constants/index.js, src/hooks/useTokenList.js, src/pages/components/Header/index.js, src/pages/components/HeaderAccount/index.js, src/pages/components/WalletHub/index.js, src/pages/components/useTransactionNotification/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/94)
=> fix: fix router bug

src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/96)
=> fix: chainid bug fix

src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/97)
=> fix: remove console

src/hooks/usePortal.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/98)
=> fix: fix chain id bug

public/index.html, src/pages/Shuttle/ShuttleForm/ChainSelect.js, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/99)
=> fix: test chainid

public/index.html, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/100)
=> fix: remove alert

src/pages/History/HistoryItem.js, src/pages/Shuttle/ConfirmModal/BtcConfirmTips.js, src/pages/Shuttle/TokenList/TokenItem.js, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/103)
=> fix: fix toast width bug

src/hooks/useTransaction.js, src/pages/components/WalletHub/index.js, src/state/transaction.js, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/106)
=> fix: fix render wallet hub history

public/index.html, src/pages/History/index.js, src/pages/Shuttle/ShuttleForm/TokenSelect.js, src/pages/Shuttle/TokenList/CommonTokens.js, src/pages/Shuttle/TokenList/index.js, src/pages/components/ChainItem/index.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/107)
=> fix: fix ui check bug

src/pages/Shuttle/ShuttleForm/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/109)
=> fix: several bugs

package.json, src/pages/App.js, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/110)
=> feat(sentry): add Sentry service

src/pages/History/HistoryItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/112)
=> fix(history): display_symbol

src/pages/Shuttle/TokenList/TokenSearch.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/113)
=> fix: fix autocomplete

src/hooks/useTokenList.js, src/pages/History/Progress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/114)
=> fix: #ap105a

src/hooks/useTransaction.js
1. remove BTC-in transactions when append the data
2. return [] when the portal address is null
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/115)
=> fix(useTransaction): several bugs

src/hooks/useTransaction.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/Out.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/116)
=> fix(history): minus the fee when cache to local

src/hooks/useTransaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/118)
=> fix(history): whether has native token

src/pages/Shuttle/ShuttleForm/index.js, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/120)
=> fix: #aqxuu0

src/pages/Shuttle/ShuttleForm/FromToken.js, src/pages/Shuttle/ShuttleForm/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/122)
=> fix: #aqxvdq

src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/123)
=> chore(): add debug console

src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/124)
=> chore(in.js): add console

src/hooks/useTransaction.js, src/pages/History/index.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/125)
=> fix(hisotry): filter tx_type

src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/126)
=> fix(approve): approve-usdt reset to zero

src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/127)
=> chore: delete console

src/hooks/useTransaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/128)
=> fix(approve): reset the status of approve to error

public/locales/en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/129)
=> fix: modify i18n

src/hooks/useWeb3Network.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/133)
=> fix(balance): web3 balance

src/hooks/useWeb3Network.js, src/pages/History/Progress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/132)
=> fix: #ar119x

src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/134)
=> fix: origin  === cfx erc20 token need not approve

src/constants/chainConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/135)
=> fix(chainconfig): ok scan

src/pages/History/HistoryItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/138)
=> fix: pending history detail default display

src/pages/Home/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/140)
=> fix: home mobile adaptation

src/hooks/usePortal.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/142)
=> fix: mobile error

src/hooks/usePortal.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/145)
=> fix(portal): account

src/hooks/usePortal.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/146)
=> fix(): portal account

package.json, src/state/transaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/147)
=> fix(api): modity to polyfill api

package.json, src/hooks/usePortal.js, src/state/transaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/148)
=> fix(api): polyfill

src/components/Tooltip/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/150)
=> fix: modify the ui style

public/locales/en.json, public/locales/zh-CN.json, src/components/Link/index.js, src/components/Tooltip/index.js, src/constants/index.js, src/pages/History/HistoryItem.js, src/pages/Shuttle/ClaimModal/FirstStep.js, src/pages/Shuttle/ClaimModal/SecondStep.js, src/pages/Shuttle/ClaimModal/index.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/In.js, src/pages/Shuttle/ConfirmModal/ShuttleButton/Out.js, src/pages/Shuttle/ShuttleForm/FromToken.js, src/pages/Shuttle/TokenList/TokenItem.js, src/pages/Shuttle/index.js, src/pages/components/TransactionReceiptionModal/index.js, tailwind.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/155)
=> feat: claim ui

src/pages/History/Progress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/160)
=> fix: fix claim text color

src/pages/History/Progress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/161)
=> fix: fix dot color

public/locales/en.json, public/locales/zh-CN.json, src/pages/History/HistoryItem.js, src/pages/History/Progress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/162)
=> fix: fix progress display

src/components/Link/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/163)
=> fix: modify link

src/pages/Shuttle/ClaimModal/FirstStep.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/164)
=> fix: fix i18n

src/components/Popover/index.js, src/components/Tooltip/index.js, src/pages/Shuttle/ClaimModal/FirstStep.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/165)
=> feat: fix display ui bug

src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/168)
=> fix(calculategasmargin): add toString to calculateGasMargin

src/constants/chainConfig.js, src/hooks/useWallet.js, src/pages/History/HistoryItem.js, src/pages/History/Progress.js, src/pages/components/Account/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/170)
=> feat(robustness): system robustness for no-supported chain

src/components/Alert/index.js, src/pages/Shuttle/ClaimModal/SecondStep.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/171)
=> fix: bug fix #dzr6rz

src/pages/Shuttle/ClaimModal/SecondStep.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/174)
=> fix: #dzxx6d

src/components/Link/index.js, src/pages/History/HistoryItem.js, src/pages/Shuttle/ClaimModal/FirstStep.js, src/pages/Shuttle/ClaimModal/SecondStep.js, src/pages/Shuttle/TokenList/TokenItem.js, src/pages/components/WalletHub/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/175)
=> fix: Bug fix

src/components/Input/index.js, src/hooks/useTransaction.js, src/pages/components/ClaimButton/index.js, src/pages/components/useClaimNotification/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/176)
=> fix: #e5gmkk

src/pages/components/ClaimButton/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/179)
=> fix: notification close

src/hooks/useShuttleData.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/181)
=> fix(btc-in): add minival value to btc-in

src/pages/History/HistoryItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/182)
=> fix: fix status display

package.json, src/components/Alert/index.js, src/components/Button/index.js, src/components/Input/index.js, src/components/Link/index.js, src/components/Tag/index.js, src/i18n.js
remove unnecessary useMemo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/183)
=> Feature change component

src/pages/Shuttle/ClaimModal/ShuttleButton/In.js, src/pages/Shuttle/ClaimModal/ShuttleButton/Out.js, src/pages/Shuttle/ConfirmModal/CbtcShuttleOutButton.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/191)
=> fix(estimategas): #ebeye7:estimate before send tx

src/hooks/usePortal.js, src/hooks/useWeb3Network.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/193)
=> fix: crash in Confirmmodal when portal locked

src/pages/Shuttle/ClaimModal/ShuttleButton/In.js, src/pages/Shuttle/ClaimModal/ShuttleButton/Out.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/192)
=> chore: update button code

src/pages/History/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/196)
=> fix(history): #e5mp73:modify sorting

src/hooks/useTransaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/197)
=> fix(usetransaction): #f2826a: sort first

src/pages/Shuttle/ClaimModal/index.js, src/pages/components/Header/index.js, src/pages/components/MobileFooter/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/198)
=> fix: fix last bug

src/constants/contractConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/203)
=> feat(contractaddress): update contract address of prod

src/pages/components/ClaimButton/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/204)
=> fix(claimbutton): set claimShown to false by default

src/hooks/useClaimedTx.js, src/state/transaction.js, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/206)
=> chroe: console

src/hooks/useClaimedTx.js, src/state/transaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/207)
=> chore(console): add console log

src/hooks/useClaimedTx.js, src/hooks/useTransaction.js, src/state/transaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/208)
=> chore(console): debug log

src/hooks/useClaimedTx.js, src/hooks/useTransaction.js, src/pages/App.js, src/state/transaction.js, src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/209)
=> feat: maintenance route

src/pages/App.js, src/pages/Home/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/210)
=> feat(home): modify route

src/i18n.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/211)
=> feat(i18n): modify useSuspense

src/pages/components/LanguageButton/index.js, src/pages/components/MobileFooter/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/214)
=> fix(language): undefined language

src/pages/Shuttle/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/217)
=> fix: #gaa3g6

src/pages/Shuttle/TokenList/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/218)
=> fix: add min height for token list

src/hooks/useTransaction.js
format CFX address to the same format when getting transactions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/220)
=> fix(usetransaction): format CFX address to the same format

src/constants/chainConfig.js, src/constants/contractConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/221)
=> feat(heco): contract address of prod

src/hooks/useTransaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/223)
=> fix: fix bug

package.json, src/hooks/usePortal.js, src/pages/components/TransactionReceiptionModal/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/227)
=> fix: import @cfxjs/use-wallet to connect wallet

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/229)
=> fix: upgrade use-wallet

src/constants/chainConfig.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/rigel/232)
=> feat: modify mainnet name
